/* AUTO-GENERATED by scripts/scan-lyrics.mjs — do not edit */
/* Source: content/lyrics/*.txt */

export type GeneratedLyric = {
  id: string
  title: string
  trackId: string | null
  body: string | null
}

export const generatedLyrics: GeneratedLyric[] = [
  {
    "id": "lyric-1",
    "title": "The Deal",
    "trackId": "track-1",
    "body": "Finger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\n\nSitting in the Crib, Feeling so Bold\nFinger on the trigger hand on the gold\nLooking for truth, only seeing lies\nFeeling mother’s pain, forgetting father’s advice\nHands full of cash, heart full of fire\nWishing for my desire\nLooking for truth only seeing lies\n\nFinger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\nFinger on the trigger Hand on the Gold\n\nFalse dreams filling my head,\nWhile searching for bullets to fight off the dead\nBrothers in pain Brothers laid to rest\nPrison is a thought I can’t resist\nOut of the blue they crash through the door,\nGrab me by the throat, and threw me to the floor\n\nFinger on the Trigger\nFinger on the trigger Hand on the gold\nFinger on the Trigger, Hand on the Gold\nBrothers in pain, Brothers laid to rest\nFinger on the Trigger hey eee yea\n\nGod Said, Wake up young man before it’s too late\nThe next ten years will flood with tears to the ones that you love,\nand the ones that you don’t\n\nWith that in mind and reaching for my soul\nGrasping for air before getting old\nLooking for the sun in my father’s eyes\nbefore it’s too late, or my demise\nFinger on the trigger hand on the gold\nFinger on the trigger hand on the gold\nLooking for the sun in my father’s eyes\nLooking for the sun in my father’s eyes\nLooking for the sun in my father’s eyes\n\nFinger on the trigger hand on the gold\nFinger on the trigger hand on the gold\nGOLD GOLD"
  },
  {
    "id": "lyric-2",
    "title": "Soldier",
    "trackId": "track-2",
    "body": "Iran, Afghanistan, Pakistan, Iraq, Vietnam, Can’t look back\nWas young, dumb, my father’s son, owed it to the war.\nWas a man, not like before\nGave my mind, my body, gave my soul\n\nCHORUS\nTake me to the Lord, cause I gave my soul\nI’m a soldier, getting colder, I’ve been wounded\nTake me to the Lord\nCause I gave my soul\nI’m a soldier, getting colder, I’ve been wounded, wounded\n\nNever feared the thought of getting killed or getting old\nAs a soldier I would fight like I’ve never fought before\nI killed, I died, dear God I cried, ‘Is it a lie, will I die?’\nA bad dream I had once before\nForgotten not forgiven, misunderstood, crucified, vilified, nearly lost our pride\nPart of me died\nI’m a warrior, older that before, a lot less sober than I was before the war\n\nCHORUS\n\nBodies bleeding, guns blazing, fires burning, Jesus take me to the Lord\nAs our blood smothers the battleground floor\nWounded, Wounded, Wounded from the war\nNot the man I was once before\nDon’t want to feel the pain I once felt\nDon’t want to feel the pain I once dealt\nDon’t want to remember those days anymore\nDon’t want to remember those days on the killing floor\nDon’t want to remember those days anymore\n\nIran, Afghanistan, Pakistan, Iraq, Vietnam, Can’t look back\nIran, Afghanistan, Pakistan, Iraq, Vietnam, Can’t look back\n\nCHORUS\n\nIran, Afghanistan, Pakistan, Iraq, Vietnam, Can’t look back\nDon’t want to feel the pain I once felt\nDon’t want to feel the pain I once felt\nDon’t want to feel the pain I once felt"
  },
  {
    "id": "lyric-3",
    "title": "Road to Redemption",
    "trackId": "track-3",
    "body": "The road to redemption, to the soul of my dreams\nIs paved with broken pieces of heartache and grief\nNo one’s the winner at the end of the line\nJust pictures and memories lost in time\nEmpty pockets that were once filled with gold\nNo woman at my side to keep me warm from the cold\nBrothers lost in a world we didn’t understand\nCompromising my integrity and forcing my hand\nWhen the verdict comes and it’s time to pay\nToo late to look for answers on judgement day\n\nClose your eyes, close your eyes, leave it all behind\n\nLocked in iron from head to toe\nThe outlaw life you thought you loved\nThe damage around you cannot be assessed\nFor a roadmap filled with shortcuts what could you expect\nFamily hurt and torn apart, reaching deep within my heart\nAsking for God’s forgiveness alone in my cell,\nThoughts filling my mind about the fires of hell\nOn the Road to Redemption to the soul of my dreams\n\nClose your eyes, close your eyes, leave it all behind\n\nThe Gladiators here stand alone,\nSome of the most talented men I’ve ever known\nTattooed in ink from head to toe\nThese warriors, these soldiers, these lost souls\nFrozen in concrete and steel\nA period of discovery, a time of strength\nCounting the days in my sleep\nWill I walk out and be forgiven for my sins\nThe blood, the glory, the lost time\n\nClose your eyes, Close your eyes, leave it all behind\nClose your eyes, Close your eyes, leave it all behind\n\nYou must close your eyes and leave it all behind\nThe story ends here, the poetry begins\nLife imitating art without my consent\nOn the road to redemption to the soul of my dreams\nOn the road to redemption to the soul of my dreams\nOn the road to redemption to the soul of my dreams\n\nClose your eyes, Close your eyes, leave it all behind\nTo the soul of my dreams\nTo the soul of my dreams\nTo the soul of my dreams"
  },
  {
    "id": "lyric-4",
    "title": "Renaissance Man",
    "trackId": "track-4",
    "body": "A story of struggle, triumph, loss, and pain,\nSquandered a fortune at a very young age,\nIncarceration, fascination, concentration, renewal of life for those who believe\nChrist died on the cross for another man’s sins\nSo you and I can breathe\nI can Breathe\n\nRenaissance, Renaissance, Renaissance, Renaissance Man\n\nThis whirlwind of time passing us by at the speed of light in the night for those who can see\nLast week I was a young boy, today a man\nTomorrow a corpse in a coffin in a gravesite forgotten\nFor those who knew me as a friend, a friend\nIn a gravesite forgotten\n\nRenaissance Renaissance, Renaissance Renaissance Man\nI’m a Renaissance Man\n\nI’m a Renaissance Man\nI’ve been reborn resurrected\nThis time not neglected I’m ready to make a stand\nTo Live my vision, to live my vision\nAnd see my dreams to rise above the ashes like a burning flame.\nLike a burning flame.\n\nThis time This time I’ll listen\nI’ll take direction I’ll find my way\nFor those who have forgotten I’m here to stay\nI’m the Renaissance Man\nI’m the Renaissance Man\n\nI’m here to stay Renaissance Man I’m here to stay\n\nRenaissance, Renaissance, Renaissance Man"
  },
  {
    "id": "lyric-5",
    "title": "Misfit from Your Past",
    "trackId": "track-5",
    "body": "I’m a hard drinking fist fighting man\nLive life on the edge a bottle of Jack in my hand\nI’m driving in the fast lane with blood on my face and beer on my breath\nMy heart is broken and I can’t quit smokin’\nDoc says, soon I’ll be chokin’\n\nLooking for trouble in all the right places\nWhy I survived when the rest didn’t make it\nOnly God knows why, God knows why, makes me want to cry\nFancy cars, cheap bars, how did it go this far?\nNo one there when I’m full of pain\nHundred dollar bills in my hands and a pocket full of change, CHANGE!\n\nI’m the misfit from your past\nI leave home when it’s dark, I come back when the sun’s up\nI eat dinner regularly at a truck stop\nI been banged up and broke, seen the inside of prison and nearly had a stroke\nI lie awake at night and wonder if the sun will ever shine, ever shine on my side of town\nThe dark side of town\nBut that rain boy, oh that rain just keeps pouring down\n\nI’m the misfit from your past, how long could it possibly last\nI’m the misfit from your past, how long could it possibly last\n\nFancy cars and cheap bars, how did it go this far?\nNo one there when I’m full of pain\nHundred dollar bills in my hands and a pocket full of change."
  },
  {
    "id": "lyric-6",
    "title": "Crusade",
    "trackId": "track-6",
    "body": "Poets prophets rebels, patriots and thieves\nCrusading against nations we’ve never seen\nSlaughtering one another over religious beliefs, armies, Arabs and oil\nDictators in war\nWhat are we fighting for\nDiamonds gold and greed\nSupersonic jets, war machines\nBack alley deals threatening the air we breathe\nThreatening the air we breathe\n\nPolitics and religion another man’s vision of how the world should be run\nFuck our opinion\nFuck our opinion\n\nWho am I, who am I to question the length of this life\nThe mere stone mason who chose his plight\nIn this world of discontent who do we trust before the world turns to dust\nAs I stand here on Arab soil\n\nOne of God’s soldiers, that’s who I am, faithful at his side\nPoets, prophets rebels patriots and thieves\nPoets, prophet rebels patriots and thieves\n\nOne of God’s soldiers, one of God’s soldiers, that’s who I am"
  },
  {
    "id": "lyric-7",
    "title": "City of Angels",
    "trackId": "track-7",
    "body": "I saw an angel just the other day,\nWalking down Sunset in the pouring rain\nMulti-million dollar homes, expensive cars\nShopping on Rodeo Drive with a platinum card.\nNearly a thousand bank robberies a year, three a day,\nTake place in Los Angeles, as we pray\nNearly a thousand murders committed each year,\nLeaving us all in a state of fear.\n\nOver 300,000 gang members, slaughtering each other in the streets\n30,000 police officers trying to keep the peace\nIn the city of angels next to the sea, gridlock on the freeway nearly every day\n\nHorns blowing, sirens screaming, jets roaring overhead, radiators steaming,\nEveryone in a hurry to go somewhere or nowhere\nDon’t have time or patience\nNo one seems to care\nAbout you or me or the people next door\nI’ve lived here for ten years I don’t know their names, does it matter?\nWhat are they gonna do for me\nI want a bigger house, and a faster car, flashy clothes, more credit cards\nI can’t keep up with all my dreams, In the city of angels it’s hard to breathe\n\n76,000 homeless living in the streets\nDon’t bother me with your problems I’m trying to decide where to eat\nOver 40,000 Veterans who fought our wars\nNo place to live, we slammed the door\nForget their dreams, why should we care,\nI didn’t tell them to go over there.\nIt’s not my fault they live in the streets,\nwhy should I help them, no one helps me\n\nIn the city of angels it’s hard to sleep\n110 at the beach\n\nI saw an angel just the other day, Walking down sunset in pouring rain.\nI saw an angel just the other day, Walking down sunset in pouring rain."
  },
  {
    "id": "lyric-8",
    "title": "Utopia",
    "trackId": "track-8",
    "body": "Bullets from heaven, angels from hell\nBlood on the sidewalk with stories to tell\nYoung men with guns, children on the run\nEducation a lost art form with history of the past\nA hole in my heart, blood in my soul\nI must get ahead before I get old.\nDeath and destruction, tyranny in the world\nBombing the high schools instead of cruising for girls\nSome say this is the fable that my brothers will tell\nAbout a place called Earth that rose from Hell\nIt once was a place for dreams to breathe\nBefore the great Apocalypse and now the freeze\nHoles in the earth Fire in the sky\nBodies on the streets with people just walking by.\nWhatever happened to my brothers and those stories of old\nBefore the blood on the sidewalk and the bullet in my soul\nBullets from Heaven, angels from Hell\nBlood on the sidewalk with stories to tell\nBullets from Heaven, angels from Hell\nBlood on the sidewalk with your story to tell"
  },
  {
    "id": "lyric-9",
    "title": "Stars On The SideWalk",
    "trackId": "track-9",
    "body": null
  },
  {
    "id": "lyric-10",
    "title": "White Stripes Black Tar",
    "trackId": "track-10",
    "body": null
  }
]
