/* AUTO-GENERATED by scripts/scan-media.mjs — do not edit */
/* Drop files in public/images and public/music, then restart/rebuild. */

export type GeneratedGalleryImage = {
  id: string
  src: string
  alt: string
  caption?: string
}

export type GeneratedTrack = {
  id: string
  title: string
  src: string
  filename: string
  downloadName: string
}

export const generatedHeroImage: string | null = null

export const generatedGalleryImages: GeneratedGalleryImage[] = []

export const generatedTracks: GeneratedTrack[] = []
