import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const lyricsDir = join(root, 'content/lyrics')
const outFile = join(root, 'src/config/lyrics.generated.ts')

/** Album order — matches public/music where files exist */
const TRACK_ORDER = [
  { key: 'deal', title: 'The Deal', trackId: 'track-1' },
  { key: 'soldier', title: 'Soldier', trackId: 'track-2' },
  { key: 'road', title: 'Road to Redemption', trackId: 'track-3' },
  { key: 'renaissance', title: 'Renaissance Man', trackId: 'track-4' },
  { key: 'misfit', title: 'Misfit from Your Past', trackId: 'track-5' },
  { key: 'crusade', title: 'Crusade', trackId: 'track-6' },
  { key: 'city', title: 'City of Angels', trackId: 'track-7' },
  { key: 'utopia', title: 'Utopia', trackId: 'track-8' },
  { key: 'stars', title: 'Stars On The SideWalk', trackId: 'track-9' },
  { key: 'white', title: 'White Stripes Black Tar', trackId: 'track-10' },
]

function cleanLyrics(text) {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function scan() {
  mkdirSync(lyricsDir, { recursive: true })

  const lyrics = TRACK_ORDER.map((track, index) => {
    const path = join(lyricsDir, `${track.key}.txt`)
    const body = existsSync(path)
      ? cleanLyrics(readFileSync(path, 'utf8'))
      : null

    return {
      id: `lyric-${index + 1}`,
      title: track.title,
      trackId: track.trackId,
      body,
    }
  })

  const contents = `/* AUTO-GENERATED by scripts/scan-lyrics.mjs — do not edit */
/* Source: content/lyrics/*.txt */

export type GeneratedLyric = {
  id: string
  title: string
  trackId: string | null
  body: string | null
}

export const generatedLyrics: GeneratedLyric[] = ${JSON.stringify(lyrics, null, 2)}
`

  mkdirSync(join(root, 'src/config'), { recursive: true })
  writeFileSync(outFile, contents, 'utf8')

  const withText = lyrics.filter((l) => l.body).length
  console.log(`[scan-lyrics] ${withText} of ${lyrics.length} songs have lyrics`)
}

scan()
