import { readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, extname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const imagesDir = join(root, 'public/images')
const musicDir = join(root, 'public/music')
const outFile = join(root, 'src/config/media.generated.ts')

const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'])
const AUDIO_EXT = new Set(['.mp3', '.wav', '.m4a', '.ogg', '.aac', '.flac'])
const HERO_NAMES = new Set(['hero', 'cover', 'portrait'])

/** Natural sort: 1-a, 2-b, 10-c */
function naturalCompare(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' })
}

function listFiles(dir, allowed) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((name) => !name.startsWith('.'))
    .filter((name) => allowed.has(extname(name).toLowerCase()))
    .sort(naturalCompare)
}

function titleFromFilename(filename) {
  const base = basename(filename, extname(filename))
  return base
    .replace(/^\d+[-_\s.]+/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase()) || base
}

function isHeroFile(filename) {
  const base = basename(filename, extname(filename)).toLowerCase()
  return HERO_NAMES.has(base)
}

function scan() {
  const imageFiles = listFiles(imagesDir, IMAGE_EXT)
  const heroFile = imageFiles.find(isHeroFile) ?? null
  const galleryFiles = imageFiles.filter((f) => !isHeroFile(f))

  const galleryImages = galleryFiles.map((file, index) => {
    const title = titleFromFilename(file)
    return {
      id: `img-${index + 1}`,
      src: `/images/${file}`,
      alt: title || 'Michael Stone',
      caption: title || undefined,
    }
  })

  const audioFiles = listFiles(musicDir, AUDIO_EXT)
  const tracks = audioFiles.map((file, index) => ({
    id: `track-${index + 1}`,
    title: titleFromFilename(file),
    src: `/music/${file}`,
    filename: file,
    downloadName: file,
  }))

  const heroImage = heroFile ? `/images/${heroFile}` : galleryImages[0]?.src ?? null

  const contents = `/* AUTO-GENERATED by scripts/scan-media.mjs — do not edit */
/* Drop files in public/images and public/music, then restart/rebuild. */

export type GeneratedGalleryImage = {
  id: string
  src: string
  alt: string
  caption?: string
}

export type GeneratedTrack = {
  id: string
  title: string
  src: string
  filename: string
  downloadName: string
}

export const generatedHeroImage: string | null = ${JSON.stringify(heroImage)}

export const generatedGalleryImages: GeneratedGalleryImage[] = ${JSON.stringify(galleryImages, null, 2)}

export const generatedTracks: GeneratedTrack[] = ${JSON.stringify(tracks, null, 2)}
`

  mkdirSync(join(root, 'src/config'), { recursive: true })
  writeFileSync(outFile, contents, 'utf8')

  console.log(
    `[scan-media] ${galleryImages.length} photos, ${tracks.length} tracks` +
      (heroImage ? `, hero: ${heroImage}` : ', no hero image'),
  )
}

scan()
